version: "3.9"

services:
  web:
    image: alwayswannaly/chessevents-frontend:1.0
    build:
      context: ./web
      dockerfile: web.dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "./web:/app"
      - "node_modules:/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - "api"

  api:
    image: alwayswannaly/chessevents-backend:1.0
    platform: linux/x86_64
    build:
      context: ./api
      dockerfile: api.dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: development
    env_file: api/.env
    depends_on:
      - "database"
      - "redis"
    volumes:
      - ./api:/app

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  sidekiq:
    image: alwayswannaly/chessevents-jobs:1.0
    build:
      context: ./api
      dockerfile: api.dockerfile
    platform: linux/x86_64
    depends_on:
      - api
      - database
      - redis
    env_file: api/.env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-init.sh
  
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - api
      - web
    ports:
      - '8000:8000'

volumes:
  node_modules:
  db_data:
  redis_data: