version: "3"

services:
  web:
    image: alwayswannaly/chessevents:frontend
    build:
      context: ./web
      dockerfile: web.dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
